name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Base
      run: |
        make base

    - name: Build
      run: |
        make build

    - name: snyk
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make snyk SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}

    - name: Jest
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make jest

    - name: Codecov
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make codecov CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}

    - name: Slack
      run: |
        make slack SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}
