name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Base
      run: |
        make base -B

    - name: Build
      run: |
        make build -B

    - name: Snyk
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make snyk SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} -B

    - name: Jest
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make jest -B

    - name: Codecov
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make codecov CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} -B

    - name: Compress
      if: ${{ github.event_name == 'push' }}
      run: |
        make compress -B

    - name: Terraform Base
      if: ${{ github.event_name == 'push' }}
      run: |
        make tf_base TF_TOKEN=${{ secrets.TF_TOKEN }} -B

    - name: Terraform Init
      if: ${{ github.event_name == 'push' }}
      run: |
        make tf_init TF_TOKEN=${{ secrets.TF_TOKEN }} -B

    - name: Terraform Apply
      if: ${{ github.event_name == 'push' }}
      run: |
        make tf_apply AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -B

    - name: Slack
      if: ${{ github.event_name == 'push' }}
      run: |
        make slack SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }} -B
