name: Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Base
      run: |
        make base

    - name: Build
      run: |
        make build

    - name: Jest
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make jest

    - name: Codecov
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make codecov CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: app/node_modules/

  Snyk:
    name: Snyk
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Build
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact

    - name: Check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}