name: Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:

  Base:
    name: Base
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Base
      run: |
        make base

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Base
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        make build

  Jest:
    name: Jest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Base
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Jest
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make jest

    - name: Codecov
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make codecov CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}

  Snyk:
    name: Snyk
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Base
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Snyk
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make snyk SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}